spring:
  datasource:
    url: jdbc:mysql://47.121.181.198:3306/my_blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: o#DwN&JSa56
    driver-class-name: com.mysql.cj.jdbc.Driver

